version: "3.8"

services:
  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:development@postgres_dev:5432/ganapatihakasa_dev?schema=public
    env_file:
      - .env
    depends_on:
      - postgres_dev
    volumes:
      - .:/app
      - /app/node_modules

  postgres_dev:
    image: postgres:16
    container_name: postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development
      POSTGRES_DB: ganapatihakasa_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
